name: Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: npx markdownlint-cli2 "**/*.md" "#node_modules"
